/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Jasa;
import model.Jenis;
import model.Pengeluaran;
import model.Harga;

/**
 *
 * @author User
 */
public class FrameApp extends javax.swing.JFrame {
         // Array untuk menyimpan admin
    private static final ArrayList<Harga> hargaList = new ArrayList<>();
    private static final ArrayList<Jasa> jasaList = new ArrayList<>();
    private static final ArrayList<Jenis> jenisList = new ArrayList<>();
    private static final ArrayList<Pengeluaran> pengeluaranList = new ArrayList<>();

    /**
     * Creates new form FrameApp
     */
    public FrameApp() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Content = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pnlPengeluaran = new javax.swing.JPanel();
        txtIdPengeluaran = new javax.swing.JTextField();
        txtKeteranganPengeluaran = new javax.swing.JTextField();
        txtNominalPengeluaran = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnInputPengeluaran = new javax.swing.JButton();
        dtTanggal = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        txtIdJenisPengeluaran = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtIdUsersPengeluaran = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        pnlJenis = new javax.swing.JPanel();
        txtIdJenis = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnInputJenis = new javax.swing.JButton();
        pnlJasa = new javax.swing.JPanel();
        txtIdJasa = new javax.swing.JTextField();
        txtKeteranganJasa = new javax.swing.JTextField();
        txtNominalJasa = new javax.swing.JTextField();
        txtIdUsersJasa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnInputJasa = new javax.swing.JButton();
        pnlHarga = new javax.swing.JPanel();
        txtIdHarga = new javax.swing.JTextField();
        txtKeteranganHarga = new javax.swing.JTextField();
        txtNominalHarga = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnInputHarga = new javax.swing.JButton();
        txtIdUsersHarga = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        btnPengeluaran = new javax.swing.JButton();
        btnJenis = new javax.swing.JButton();
        btnJasa = new javax.swing.JButton();
        btnHarga = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Content.setBackground(new java.awt.Color(153, 204, 255));
        Content.setLayout(new java.awt.CardLayout());

        pnlHome.setBackground(new java.awt.Color(255, 102, 153));

        jLabel9.setBackground(new java.awt.Color(255, 204, 204));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 204, 204));
        jLabel9.setText("Selamat Datang di Loundry Hikmah");

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        Content.add(pnlHome, "card6");

        pnlPengeluaran.setBackground(new java.awt.Color(255, 102, 153));
        pnlPengeluaran.setForeground(new java.awt.Color(255, 255, 255));

        txtIdPengeluaran.setBackground(new java.awt.Color(255, 255, 255));
        txtIdPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPengeluaranActionPerformed(evt);
            }
        });

        txtKeteranganPengeluaran.setBackground(new java.awt.Color(255, 255, 255));
        txtKeteranganPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeteranganPengeluaranActionPerformed(evt);
            }
        });

        txtNominalPengeluaran.setBackground(new java.awt.Color(255, 255, 255));
        txtNominalPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNominalPengeluaranActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("KETERANGAN");

        jLabel13.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("ID PENGELUARAN");

        jLabel14.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("TANGGAL");

        btnInputPengeluaran.setText("INPUT");
        btnInputPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputPengeluaranActionPerformed(evt);
            }
        });

        dtTanggal.setBackground(new java.awt.Color(255, 255, 255));
        dtTanggal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        dtTanggal.setForeground(new java.awt.Color(255, 255, 255));
        dtTanggal.setFocusTraversalPolicyProvider(true);
        dtTanggal.setInheritsPopupMenu(true);

        jLabel20.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("NOMINAL");

        txtIdJenisPengeluaran.setBackground(new java.awt.Color(255, 255, 255));
        txtIdJenisPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdJenisPengeluaranActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("ID JENIS");

        txtIdUsersPengeluaran.setBackground(new java.awt.Color(255, 255, 255));
        txtIdUsersPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdUsersPengeluaranActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("ID USERS");

        javax.swing.GroupLayout pnlPengeluaranLayout = new javax.swing.GroupLayout(pnlPengeluaran);
        pnlPengeluaran.setLayout(pnlPengeluaranLayout);
        pnlPengeluaranLayout.setHorizontalGroup(
            pnlPengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPengeluaranLayout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(pnlPengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInputPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPengeluaranLayout.createSequentialGroup()
                        .addGroup(pnlPengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(46, 46, 46)
                        .addGroup(pnlPengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdUsersPengeluaran, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNominalPengeluaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(txtIdPengeluaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtKeteranganPengeluaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(dtTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIdJenisPengeluaran))))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pnlPengeluaranLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtIdPengeluaran, txtKeteranganPengeluaran, txtNominalPengeluaran});

        pnlPengeluaranLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel12, jLabel13, jLabel14, jLabel20, jLabel21, jLabel22});

        pnlPengeluaranLayout.setVerticalGroup(
            pnlPengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPengeluaranLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(pnlPengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPengeluaranLayout.createSequentialGroup()
                        .addGroup(pnlPengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPengeluaranLayout.createSequentialGroup()
                                .addGroup(pnlPengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPengeluaranLayout.createSequentialGroup()
                                        .addGroup(pnlPengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(pnlPengeluaranLayout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel12))
                                            .addGroup(pnlPengeluaranLayout.createSequentialGroup()
                                                .addComponent(txtIdPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(dtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtKeteranganPengeluaran)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNominalPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtIdJenisPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtIdUsersPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInputPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pnlPengeluaranLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dtTanggal, txtIdPengeluaran, txtKeteranganPengeluaran, txtNominalPengeluaran});

        Content.add(pnlPengeluaran, "card3");

        pnlJenis.setBackground(new java.awt.Color(255, 102, 153));

        txtIdJenis.setBackground(new java.awt.Color(255, 255, 255));

        txtNama.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("ID JENIS");

        jLabel16.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("NAMA");

        btnInputJenis.setText("INPUT");
        btnInputJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputJenisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlJenisLayout = new javax.swing.GroupLayout(pnlJenis);
        pnlJenis.setLayout(pnlJenisLayout);
        pnlJenisLayout.setHorizontalGroup(
            pnlJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJenisLayout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addGroup(pnlJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlJenisLayout.createSequentialGroup()
                        .addGroup(pnlJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(41, 41, 41)
                        .addGroup(pnlJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnInputJenis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        pnlJenisLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel15, jLabel16});

        pnlJenisLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtIdJenis, txtNama});

        pnlJenisLayout.setVerticalGroup(
            pnlJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJenisLayout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(pnlJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdJenis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(pnlJenisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnInputJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pnlJenisLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtIdJenis, txtNama});

        Content.add(pnlJenis, "card4");

        pnlJasa.setBackground(new java.awt.Color(255, 102, 153));

        txtIdJasa.setBackground(new java.awt.Color(255, 255, 255));

        txtKeteranganJasa.setBackground(new java.awt.Color(255, 255, 255));

        txtNominalJasa.setBackground(new java.awt.Color(255, 255, 255));
        txtNominalJasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNominalJasaActionPerformed(evt);
            }
        });

        txtIdUsersJasa.setBackground(new java.awt.Color(255, 255, 255));
        txtIdUsersJasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdUsersJasaActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("ID JASA");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("KETERANGAN");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("NOMINAL");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("ID USERS");

        btnInputJasa.setText("INPUT");
        btnInputJasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputJasaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlJasaLayout = new javax.swing.GroupLayout(pnlJasa);
        pnlJasa.setLayout(pnlJasaLayout);
        pnlJasaLayout.setHorizontalGroup(
            pnlJasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJasaLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(pnlJasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInputJasa, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlJasaLayout.createSequentialGroup()
                        .addGroup(pnlJasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43)
                        .addGroup(pnlJasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKeteranganJasa)
                            .addComponent(txtNominalJasa)
                            .addComponent(txtIdUsersJasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdJasa, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pnlJasaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtIdJasa, txtIdUsersJasa, txtKeteranganJasa, txtNominalJasa});

        pnlJasaLayout.setVerticalGroup(
            pnlJasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJasaLayout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(pnlJasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtIdJasa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 25, Short.MAX_VALUE)
                .addGroup(pnlJasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtKeteranganJasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 25, Short.MAX_VALUE)
                .addGroup(pnlJasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlJasaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 25, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(pnlJasaLayout.createSequentialGroup()
                        .addComponent(txtNominalJasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(txtIdUsersJasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 25, Short.MAX_VALUE)
                .addComponent(btnInputJasa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pnlJasaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtIdJasa, txtIdUsersJasa, txtKeteranganJasa, txtNominalJasa});

        Content.add(pnlJasa, "card5");

        pnlHarga.setBackground(new java.awt.Color(255, 102, 153));

        txtIdHarga.setBackground(new java.awt.Color(255, 255, 255));

        txtKeteranganHarga.setBackground(new java.awt.Color(255, 255, 255));

        txtNominalHarga.setBackground(new java.awt.Color(255, 255, 255));
        txtNominalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNominalHargaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("NOMINAL");

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID HARGA");

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("KETERANGAN");

        btnInputHarga.setText("INPUT");
        btnInputHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputHargaActionPerformed(evt);
            }
        });

        txtIdUsersHarga.setBackground(new java.awt.Color(255, 255, 255));
        txtIdUsersHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdUsersHargaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("ID USERS");

        javax.swing.GroupLayout pnlHargaLayout = new javax.swing.GroupLayout(pnlHarga);
        pnlHarga.setLayout(pnlHargaLayout);
        pnlHargaLayout.setHorizontalGroup(
            pnlHargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHargaLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(pnlHargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInputHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlHargaLayout.createSequentialGroup()
                        .addGroup(pnlHargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel11))
                        .addGap(42, 42, 42)
                        .addGroup(pnlHargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdUsersHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNominalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKeteranganHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        pnlHargaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel11, jLabel2, jLabel3, jLabel4});

        pnlHargaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtIdHarga, txtIdUsersHarga, txtKeteranganHarga, txtNominalHarga});

        pnlHargaLayout.setVerticalGroup(
            pnlHargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHargaLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(pnlHargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlHargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtKeteranganHarga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlHargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNominalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(pnlHargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtIdUsersHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnInputHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );

        pnlHargaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtIdHarga, txtKeteranganHarga, txtNominalHarga});

        Content.add(pnlHarga, "card2");

        getContentPane().add(Content, java.awt.BorderLayout.CENTER);

        Header.setBackground(new java.awt.Color(204, 0, 102));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 204));
        jLabel1.setText("JASA HIKMAH LOUNDRY");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(237, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(237, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        Menu.setBackground(new java.awt.Color(204, 0, 102));

        btnPengeluaran.setBackground(new java.awt.Color(255, 102, 153));
        btnPengeluaran.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnPengeluaran.setForeground(new java.awt.Color(0, 0, 0));
        btnPengeluaran.setText("PENGELUARAN");
        btnPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengeluaranActionPerformed(evt);
            }
        });

        btnJenis.setBackground(new java.awt.Color(255, 102, 153));
        btnJenis.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnJenis.setForeground(new java.awt.Color(0, 0, 0));
        btnJenis.setText("JENIS");
        btnJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJenisActionPerformed(evt);
            }
        });

        btnJasa.setBackground(new java.awt.Color(255, 102, 153));
        btnJasa.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnJasa.setForeground(new java.awt.Color(0, 0, 0));
        btnJasa.setText("JASA");
        btnJasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJasaActionPerformed(evt);
            }
        });

        btnHarga.setBackground(new java.awt.Color(255, 102, 153));
        btnHarga.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnHarga.setForeground(new java.awt.Color(0, 0, 0));
        btnHarga.setText("HARGA");
        btnHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHargaActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(255, 102, 153));
        btnHome.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnHome.setForeground(new java.awt.Color(0, 0, 0));
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJenis)
                    .addComponent(btnJasa)
                    .addComponent(btnHarga)
                    .addComponent(btnPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHarga, btnJasa, btnJenis, btnPengeluaran});

        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnJenis)
                .addGap(18, 18, 18)
                .addComponent(btnJasa)
                .addGap(18, 18, 18)
                .addComponent(btnHarga)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        MenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnHarga, btnJasa, btnJenis, btnPengeluaran});

        getContentPane().add(Menu, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNominalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNominalHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNominalHargaActionPerformed

    private void btnInputHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputHargaActionPerformed
        try {
            // Validasi input kosong
            if (txtIdHarga.getText().isEmpty() || 
                txtKeteranganHarga.getText().isEmpty() || 
                txtNominalHarga.getText().isEmpty() || 
                txtIdUsersHarga.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, 
                    "Semua field harus diisi!", 
                    "Error", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Validasi angka untuk ID dan password
            int idHarga = Integer.parseInt(txtIdHarga.getText());
            String keterangan = txtKeteranganHarga.getText();
            int nominal = Integer.parseInt(txtNominalHarga.getText());
            int idUsers = Integer.parseInt(txtIdUsersHarga.getText());

            // Validasi nilai tidak negatif
            if (idHarga < 0 || idUsers < 0 || nominal < 0) {
                JOptionPane.showMessageDialog(null, 
                    "ID Harga, ID Users, dan Nominal tidak boleh negatif!", 
                    "Error", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Set data ke objek Harga
            Harga objHarga = new Harga();
            objHarga.setId_harga(idHarga);
            objHarga.setKeterangan(keterangan);
            objHarga.setNominal(nominal);
            objHarga.setId_users(idUsers);
            
            // Menambahkan objek harga ke dalam ArrayList
            hargaList.add(objHarga);
            
            objHarga.infoHarga();

            // Memberi konfirmasi bahwa harga berhasil ditambahkan
            JOptionPane.showMessageDialog(null, 
                "Harga berhasil ditambahkan!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);

            // Menampilkan semua harga yang ada di ArrayList
            StringBuilder allHarga = new StringBuilder("Daftar Harga:\n");
            for (Harga harga : hargaList) {
                allHarga.append("ID: ").append(harga.getId_harga())
                        .append(", Keterangan: ").append(harga.getKeterangan())
                        .append(", Nominal: ").append(harga.getNominal())
                        .append(", ID Users: ").append(harga.getId_users())
                        .append("\n");
            }

            JOptionPane.showMessageDialog(null, allHarga.toString(), 
                "Daftar Harga", JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, 
                "ID Harga, ID Users, dan Nominal harus berupa angka!", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, 
                "Terjadi kesalahan: " + ex.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInputHargaActionPerformed

    private void txtNominalJasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNominalJasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNominalJasaActionPerformed

    private void txtNominalPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNominalPengeluaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNominalPengeluaranActionPerformed

    private void btnInputPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputPengeluaranActionPerformed
        try {
            // Validasi input kosong
            if (txtIdPengeluaran.getText().isEmpty() || 
                (dtTanggal.getDate() == null) ||
                txtKeteranganPengeluaran.getText().isEmpty() || 
                txtNominalPengeluaran.getText().isEmpty() || 
                txtIdJenisPengeluaran.getText().isEmpty() || 
                txtIdUsersPengeluaran.getText().isEmpty()){ 

                JOptionPane.showMessageDialog(null, 
                    "Semua field harus diisi!", 
                    "Error", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Validasi angka untuk id_pengeluaran dan id_jenis
            int idPengeluaran = Integer.parseInt(txtIdPengeluaran.getText());
            Date tanggal = dtTanggal.getDate();  // Ambil tanggal dari JCalendar atau DateChooser
            String keterangan = txtKeteranganPengeluaran.getText();
            int nominal = Integer.parseInt(txtNominalPengeluaran.getText());
            int idJenis = Integer.parseInt(txtIdJenisPengeluaran.getText());
            int idUsers = Integer.parseInt(txtIdUsersPengeluaran.getText());

            // Validasi nilai tidak negatif untuk id_pengeluaran dan id_jenis
            if (idPengeluaran < 0 || idJenis < 0 || nominal < 0 || idUsers < 0) {
                JOptionPane.showMessageDialog(null, 
                    "ID Pengeluaran, ID Jenis, ID Users dan Nominal tidak boleh negatif!", 
                    "Error", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Cek apakah nominal adalah angka yang valid
            if (nominal == 0) {
                JOptionPane.showMessageDialog(null, 
                    "Nominal tidak boleh nol!", 
                    "Error", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Simulasi pembuatan objek Pengeluaran
            Pengeluaran objPengeluaran = new Pengeluaran();
            objPengeluaran.setId_pengeluaran(idPengeluaran);
            objPengeluaran.setTanggal(tanggal);
            objPengeluaran.setKeterangan(keterangan);
            objPengeluaran.setNominal(nominal);
            objPengeluaran.setId_jenis(idJenis);
            objPengeluaran.setId_users(idUsers);

            // Menambahkan objek pengeluaran ke dalam ArrayList
            pengeluaranList.add(objPengeluaran);

            objPengeluaran.infoPengeluaran();

            // Memberi konfirmasi bahwa pengeluaran berhasil ditambahkan
            JOptionPane.showMessageDialog(null, 
                "Pengeluaran berhasil ditambahkan!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);

            // Menampilkan semua harga yang ada di ArrayList
            StringBuilder allPengeluaran = new StringBuilder("Daftar Pengeluaran:\n");
            for (Pengeluaran pengeluaran : pengeluaranList) {
                allPengeluaran.append("ID: ").append(pengeluaran.getId_pengeluaran())
                        .append(", Tanggal: ").append(pengeluaran.getTanggal())
                        .append(", Keterangan: ").append(pengeluaran.getKeterangan())
                        .append(", Nominal: ").append(pengeluaran.getNominal())
                        .append(", ID Users: ").append(pengeluaran.getId_users())
                        .append("\n");
            }

            JOptionPane.showMessageDialog(null, allPengeluaran.toString(), 
                "Daftar Pengeluaran", JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, 
                "ID Pengeluaran, ID Jenis, ID Users dan Nominal harus berupa angka!", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, 
                "Terjadi kesalahan: " + ex.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnInputPengeluaranActionPerformed

    private void btnInputJasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputJasaActionPerformed
        try {
            // Validasi input kosong
            if (txtIdJasa.getText().isEmpty() || 
                txtKeteranganJasa.getText().isEmpty() || 
                txtNominalJasa.getText().isEmpty() || 
                txtIdUsersJasa.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, 
                    "Semua field harus diisi!", 
                    "Error", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Parsing dan validasi angka
            int idJasa = Integer.parseInt(txtIdJasa.getText());
            String keterangan = txtKeteranganJasa.getText();
            int nominal = Integer.parseInt(txtNominalJasa.getText());
            int idUsers = Integer.parseInt(txtIdUsersJasa.getText());

            // Validasi nilai tidak negatif
            if (idJasa < 0 || nominal < 0 || idUsers < 0) {
                JOptionPane.showMessageDialog(null, 
                    "ID Jasa, Nominal,dan ID Users tidak boleh negatif!", 
                    "Error", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            // Set data ke objek Produk
            Jasa objJasa = new Jasa();
            objJasa.setId_jasa(idJasa);
            objJasa.setKeterangan(keterangan);
            objJasa.setNominal(nominal);
            objJasa.setId_users(idUsers);
            
            // Menambahkan objek jasa ke dalam ArrayList
            jasaList.add(objJasa);

            objJasa.infoJasa();

            // Memberi konfirmasi bahwa jasa berhasil ditambahkan
            JOptionPane.showMessageDialog(null, 
                "Jasa berhasil ditambahkan!", 
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);

            // Menampilkan semua harga yang ada di ArrayList
            StringBuilder allJasa = new StringBuilder("Daftar Jasa:\n");
            for (Jasa jasa : jasaList) {
                allJasa.append("ID: ").append(jasa.getId_jasa())
                        .append(", Keterangan: ").append(jasa.getKeterangan())
                        .append(", Nominal: ").append(jasa.getNominal())
                        .append(", ID Users: ").append(jasa.getId_users())
                        .append("\n");
            }

            JOptionPane.showMessageDialog(null, allJasa.toString(), 
                "Daftar Jasa", JOptionPane.INFORMATION_MESSAGE);
            

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, 
                "ID Jasa, Nominal, dan ID Users harus berupa angka!", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, 
                "Terjadi kesalahan: " + ex.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInputJasaActionPerformed

    private void btnInputJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputJenisActionPerformed
    try {
        // Validasi input kosong
        if (txtIdJenis.getText().isEmpty() || 
            txtNama.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(null, 
                "Semua field harus diisi!", 
                "Error", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validasi angka untuk ID dan password
        int idJenis = Integer.parseInt(txtIdJenis.getText());
        String nama = txtNama.getText();

        // Validasi nilai tidak negatif
        if (idJenis < 0) {
            JOptionPane.showMessageDialog(null, 
                "ID Jenis tidak boleh negatif!", 
                "Error", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        Jenis objJenis = new Jenis();
        objJenis.setId_jenis(idJenis);
        objJenis.setNama(nama);
        
        // Menambahkan objek jenis ke dalam ArrayList
        jenisList.add(objJenis);

        objJenis.infoJenis();

        // Memberi konfirmasi bahwa jenis berhasil ditambahkan
        JOptionPane.showMessageDialog(null, 
            "Jenis berhasil ditambahkan!", 
            "Success", 
            JOptionPane.INFORMATION_MESSAGE);

        // Menampilkan semua harga yang ada di ArrayList
        StringBuilder allJenis = new StringBuilder("Daftar Jenis:\n");
        for (Jenis jenis : jenisList) {
            allJenis.append("ID: ").append(jenis.getId_jenis())
                    .append(", Nama: ").append(jenis.getNama())
                    .append("\n");
        }

        JOptionPane.showMessageDialog(null, allJenis.toString(), 
            "Daftar Jenis", JOptionPane.INFORMATION_MESSAGE);

    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(null, 
            "ID Jenis harus berupa angka!", 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, 
            "Terjadi kesalahan: " + ex.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnInputJenisActionPerformed

    private void btnPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengeluaranActionPerformed
        Content.removeAll(); 
        Content.add(pnlPengeluaran);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnPengeluaranActionPerformed

    private void btnJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJenisActionPerformed
        Content.removeAll(); 
        Content.add(pnlJenis);
        Content.repaint();
        Content.revalidate();
    }//GEN-LAST:event_btnJenisActionPerformed

    private void btnJasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJasaActionPerformed
        Content.removeAll(); 
        Content.add(pnlJasa);
        Content.repaint();
        Content.revalidate();        
    }//GEN-LAST:event_btnJasaActionPerformed

    private void btnHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHargaActionPerformed
        Content.removeAll(); 
        Content.add(pnlHarga);
        Content.repaint();
        Content.revalidate();        
    }//GEN-LAST:event_btnHargaActionPerformed

    private void txtKeteranganPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeteranganPengeluaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeteranganPengeluaranActionPerformed

    private void txtIdUsersJasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdUsersJasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdUsersJasaActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        Content.removeAll(); 
        Content.add(pnlHome);
        Content.repaint();
        Content.revalidate(); 
    }//GEN-LAST:event_btnHomeActionPerformed

    private void txtIdJenisPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdJenisPengeluaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdJenisPengeluaranActionPerformed

    private void txtIdUsersPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdUsersPengeluaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdUsersPengeluaranActionPerformed

    private void txtIdPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPengeluaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPengeluaranActionPerformed

    private void txtIdUsersHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdUsersHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdUsersHargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton btnHarga;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnInputHarga;
    private javax.swing.JButton btnInputJasa;
    private javax.swing.JButton btnInputJenis;
    private javax.swing.JButton btnInputPengeluaran;
    private javax.swing.JButton btnJasa;
    private javax.swing.JButton btnJenis;
    private javax.swing.JButton btnPengeluaran;
    private com.toedter.calendar.JDateChooser dtTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnlHarga;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlJasa;
    private javax.swing.JPanel pnlJenis;
    private javax.swing.JPanel pnlPengeluaran;
    private javax.swing.JTextField txtIdHarga;
    private javax.swing.JTextField txtIdJasa;
    private javax.swing.JTextField txtIdJenis;
    private javax.swing.JTextField txtIdJenisPengeluaran;
    private javax.swing.JTextField txtIdPengeluaran;
    private javax.swing.JTextField txtIdUsersHarga;
    private javax.swing.JTextField txtIdUsersJasa;
    private javax.swing.JTextField txtIdUsersPengeluaran;
    private javax.swing.JTextField txtKeteranganHarga;
    private javax.swing.JTextField txtKeteranganJasa;
    private javax.swing.JTextField txtKeteranganPengeluaran;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNominalHarga;
    private javax.swing.JTextField txtNominalJasa;
    private javax.swing.JTextField txtNominalPengeluaran;
    // End of variables declaration//GEN-END:variables
}
